variables:
  CI: true

jobs:
- job: Ubuntu 16.04
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      llvm35:
        LLVM_VER: 3.5
      llvm38:
        LLVM_VER: 3.8
      llvm38_cmake:
        LLVM_VER: 3.8
        USE_CMAKE: 1
      llvm50:
        LLVM_VER: 5.0
      llvm50_cmake:
        LLVM_VER: 5.0
        USE_CMAKE: 1
      llvm60:
        LLVM_VER: 6.0
      llvm60_cuda:
        LLVM_VER: 6.0
        USE_CUDA: 1
      llvm60_cmake:
        LLVM_VER: 6.0
        USE_CMAKE: 1
      llvm60_cmake_static_no_include:
        LLVM_VER: 6.0
        USE_CMAKE: 1
        SLIB_INCLUDE_LLVM: 0
        SLIB_INCLUDE_LUAJIT: 0
      llvm60_cmake_dynamic:
        LLVM_VER: 6.0
        USE_CMAKE: 1
        STATIC_LLVM: 0
        STATIC_LUAJIT: 0
      llvm70_cuda_cmake_static_no_include:
        LLVM_VER: 7
        USE_CUDA: 1
        USE_CMAKE: 1
        SLIB_INCLUDE_LLVM: 0
        SLIB_INCLUDE_LUAJIT: 0
      llvm70_cmake_dynamic:
        LLVM_VER: 7
        USE_CMAKE: 1
        STATIC_LLVM: 0
        STATIC_LUAJIT: 0
  container: terralang/azure-pipelines:ubuntu-1604
  steps:
  - script: ./azure-pipelines/build.sh

jobs:
- job: Ubuntu 18.04
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      llvm60:
        LLVM_VER: 6.0
      llvm60_cmake:
        LLVM_VER: 6.0
        USE_CMAKE: 1
  container: terralang/azure-pipelines:ubuntu-1804
  steps:
  - script: ./azure-pipelines/build.sh

jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      llvm35:
        LLVM_VER: 3.5
      llvm38:
        LLVM_VER: 3.8
      llvm38_cmake:
        LLVM_VER: 3.8
        USE_CMAKE: 1
      llvm60:
        LLVM_VER: 6.0
      llvm60_cuda:
        LLVM_VER: 6.0
        USE_CUDA: 1
      llvm60_cmake:
        LLVM_VER: 6.0
        USE_CMAKE: 1
      llvm60_cmake_static_no_include:
        LLVM_VER: 6.0
        USE_CMAKE: 1
        SLIB_INCLUDE_LLVM: 0
        SLIB_INCLUDE_LUAJIT: 0
      llvm60_cmake_dynamic:
        LLVM_VER: 6.0
        USE_CMAKE: 1
        STATIC_LLVM: 0
        STATIC_LUAJIT: 0
      llvm70_cuda_cmake_static_no_include:
        LLVM_VER: 7
        USE_CUDA: 1
        USE_CMAKE: 1
        SLIB_INCLUDE_LLVM: 0
        SLIB_INCLUDE_LUAJIT: 0
      llvm70_cmake_dynamic:
        LLVM_VER: 7
        USE_CMAKE: 1
        STATIC_LLVM: 0
        STATIC_LUAJIT: 0
  steps:
  - script: ./azure-pipelines/build.sh
