jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  container: terralang/azure-pipelines:ubuntu-1604
  variables:
    LLVM_CONFIG: llvm-config-3.5
    CLANG: clang-3.5
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq build-essential cmake git wget
      sudo apt-get install -qq libncurses5-dev # FIXME: https://github.com/zdevito/terra/issues/307
      ./travis.sh
