jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  container: terralang:azure-pipelines:ubuntu-1604
  variables:
    LLVM_CONFIG: llvm-config-3.5
    CLANG: clang-3.5
  steps:
  - script: |
      set -x
      su -c 'apt-get update -qq'
      su -c 'apt-get install -qq build-essential cmake sudo'
      ./travis.sh
