jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  container: ubuntu:16.04
  variables:
    LLVM_CONFIG: llvm-config-3.5
    CLANG: clang-3.5
  steps:
  - script: |
      apt-get update -qq
      apt-get install -qq build-essential cmake sudo
      ./travis.sh
