pool:
  vmImage: ubuntu-16.04


jobs:
  - job: ubuntu-16.04-llvm-3.5
    container: ubuntu:16.04
    variables:
      LLVM_CONFIG: llvm-config-3.5
      CLANG: clang-3.5
    steps:
      - script: ./travis.sh
